### ISSUE TITLE
Consider adding a lazy-load JS script to improve performance in mobile phones

### ISSUE THREAD

**Issue by ghost** [futurelabmx/futurelabmx.github.io#32]
According to Google Pagespeed insights main thread is blocked from a number of things, some of them being static loaded images and external scripts like FB /  Google Analytics.

![image](https://user-images.githubusercontent.com/24773698/73142031-c7637700-404f-11ea-93ba-659a1a736e97.png)

**Comment by mtzrmzia** [comment]
Ok, lo checaré y haré un PR.
